Repository culturespot/culturespot-backend, pull requests merged in 2025-04, with the labels that each got.

#58 [CUL-85] 카카오 소셜 로그인 구현
  .github/workflows/build.yml
  CultureSpot-Domain/src/main/java/com/culturespot/culturespotdomain/core/global/exception/AuthExceptionCode.java
  CultureSpot-Domain/src/main/java/com/culturespot/culturespotdomain/core/global/exception/ExceptionStatusMapper.java
  CultureSpot-Domain/src/main/java/com/culturespot/culturespotdomain/core/post/service/PostServiceImpl.java
  CultureSpot-Domain/src/main/java/com/culturespot/culturespotdomain/core/user/entity/User.java
  CultureSpot-Domain/src/main/java/com/culturespot/culturespotdomain/core/user/repository/UserRepository.java
  CultureSpot-Domain/src/main/java/com/culturespot/culturespotdomain/core/user/service/UserService.java
  CultureSpot-Domain/src/main/java/com/culturespot/culturespotdomain/core/user/service/UserServiceImpl.java
  CultureSpot-Domain/src/main/resources/domain-application-prod.yml
  CultureSpot-Domain/src/main/resources/domain-application.yml
  CultureSpot-ServiceApi/src/main/java/com/culturespot/culturespotserviceapi/core/auth/controller/AuthController.java
  CultureSpot-ServiceApi/src/main/java/com/culturespot/culturespotserviceapi/core/auth/dto/LoginUser.java
  CultureSpot-ServiceApi/src/main/java/com/culturespot/culturespotserviceapi/core/auth/dto/response/LoginFailResponse.java
  CultureSpot-ServiceApi/src/main/java/com/culturespot/culturespotserviceapi/core/auth/dto/response/LoginSuccessResponse.java
  CultureSpot-ServiceApi/src/main/java/com/culturespot/culturespotserviceapi/core/auth/handler/OAuth2AuthenticationFailureHandler.java
  CultureSpot-ServiceApi/src/main/java/com/culturespot/culturespotserviceapi/core/auth/handler/OAuth2AuthenticationSuccessHandler.java
  CultureSpot-ServiceApi/src/main/java/com/culturespot/culturespotserviceapi/core/auth/strategy/LoginContext.java
  CultureSpot-ServiceApi/src/main/java/com/culturespot/culturespotserviceapi/core/auth/strategy/OAuth2LoginSuccessHandler.java
  CultureSpot-ServiceApi/src/main/java/com/culturespot/culturespotserviceapi/core/auth/userInfo/CustomOAuth2User.java
  CultureSpot-ServiceApi/src/main/java/com/culturespot/culturespotserviceapi/core/auth/userInfo/CustomOAuth2UserService.java
  CultureSpot-ServiceApi/src/main/java/com/culturespot/culturespotserviceapi/core/global/security/endpoint/EndpointType.java
  CultureSpot-ServiceApi/src/main/java/com/culturespot/culturespotserviceapi/core/global/security/filter/SecurityFilter.java
Labels: 기능 구현, 리팩토링, cultureSpot-Backend-Secrets 수정

#61 [CUL-265] fix: Update CORS settings for local environment on port 3000
  CultureSpot-ServiceApi/src/main/java/com/culturespot/culturespotserviceapi/core/global/security/config/CorsConfig.java
Labels: 버그 수정

#62 [CUL-265] refactor: 소셜 로그인 성공시, 헤더에 리다이렉트 URI 추가
  CultureSpot-ServiceApi/src/main/java/com/culturespot/culturespotserviceapi/core/auth/handler/OAuth2AuthenticationSuccessHandler.java
Labels: 기능 구현, 리팩토링

#60 Feature/cul 171
  CultureSpot-Batch/src/main/java/com/culturespot/culturespotbatch/job/performance/PerformanceMapper.java
  CultureSpot-Domain/src/main/java/com/culturespot/culturespotdomain/core/performance/entity/Category.java
  CultureSpot-Domain/src/main/java/com/culturespot/culturespotdomain/core/performance/entity/Event.java
  CultureSpot-Domain/src/main/java/com/culturespot/culturespotdomain/core/performance/entity/Performance.java
Labels: 기능 구현

#59 [CUL-173] 사용자 프로필 수정 및 조회
  CultureSpot-Domain/src/main/java/com/culturespot/culturespotdomain/core/global/config/KeyConfig.java
  CultureSpot-Domain/src/main/java/com/culturespot/culturespotdomain/core/global/exception/AuthExceptionCode.java
  CultureSpot-Domain/src/main/java/com/culturespot/culturespotdomain/core/global/exception/DomainExceptionCode.java
  CultureSpot-Domain/src/main/java/com/culturespot/culturespotdomain/core/global/exception/GlobalExceptionHandler.java
  CultureSpot-Domain/src/main/java/com/culturespot/culturespotdomain/core/performance/entity/Category.java
  CultureSpot-Domain/src/main/java/com/culturespot/culturespotdomain/core/refreshToken/service/RefreshTokenServiceImpl.java
  CultureSpot-Domain/src/main/java/com/culturespot/culturespotdomain/core/user/entity/User.java
  CultureSpot-Domain/src/main/java/com/culturespot/culturespotdomain/core/user/repository/UserRepository.java
  CultureSpot-Domain/src/main/java/com/culturespot/culturespotdomain/core/user/service/UserService.java
  CultureSpot-Domain/src/main/java/com/culturespot/culturespotdomain/core/user/service/UserServiceImpl.java
  CultureSpot-ServiceApi/build.gradle
  CultureSpot-ServiceApi/src/main/java/com/culturespot/culturespotserviceapi/common/CurrentUserProvider.java
  CultureSpot-ServiceApi/src/main/java/com/culturespot/culturespotserviceapi/common/security/config/CorsConfig.java
  CultureSpot-ServiceApi/src/main/java/com/culturespot/culturespotserviceapi/common/security/endpoint/EndpointType.java
  CultureSpot-ServiceApi/src/main/java/com/culturespot/culturespotserviceapi/common/security/filter/JwtAuthenticationFilter.java
  CultureSpot-ServiceApi/src/main/java/com/culturespot/culturespotserviceapi/common/security/filter/SecurityFilter.java
  CultureSpot-ServiceApi/src/main/java/com/culturespot/culturespotserviceapi/common/swagger/SwaggerErrorResponse.java
  CultureSpot-ServiceApi/src/main/java/com/culturespot/culturespotserviceapi/common/utils/CookieUtils.java
  CultureSpot-ServiceApi/src/main/java/com/culturespot/culturespotserviceapi/common/utils/response/ApiResponse.java
  CultureSpot-ServiceApi/src/main/java/com/culturespot/culturespotserviceapi/common/utils/response/NamedWrapper.java
  CultureSpot-ServiceApi/src/main/java/com/culturespot/culturespotserviceapi/core/auth/controller/AuthController.java
  CultureSpot-ServiceApi/src/main/java/com/culturespot/culturespotserviceapi/core/auth/controller/TestController.java
  CultureSpot-ServiceApi/src/main/java/com/culturespot/culturespotserviceapi/core/auth/handler/OAuth2AuthenticationSuccessHandler.java
  CultureSpot-ServiceApi/src/main/java/com/culturespot/culturespotserviceapi/core/auth/userInfo/CustomOAuth2UserService.java
  CultureSpot-ServiceApi/src/main/java/com/culturespot/culturespotserviceapi/core/auth/userInfo/CustomUserDetails.java
  CultureSpot-ServiceApi/src/main/java/com/culturespot/culturespotserviceapi/core/health/HealthCheckController.java
  CultureSpot-ServiceApi/src/main/java/com/culturespot/culturespotserviceapi/core/post/controller/PostController.java
  CultureSpot-ServiceApi/src/main/java/com/culturespot/culturespotserviceapi/core/user/controller/UserController.java
  CultureSpot-ServiceApi/src/main/java/com/culturespot/culturespotserviceapi/core/user/controller/spec/UserControllerSpec.java
  CultureSpot-ServiceApi/src/main/java/com/culturespot/culturespotserviceapi/core/user/controller/spec/description/UserControllerDescription.java
  CultureSpot-ServiceApi/src/main/java/com/culturespot/culturespotserviceapi/core/user/dto/UserProfile.java
  CultureSpot-ServiceApi/src/main/java/com/culturespot/culturespotserviceapi/core/user/dto/request/UserProfileRequest.java
  CultureSpot-ServiceApi/src/main/java/com/culturespot/culturespotserviceapi/core/user/dto/response/UserProfileResponse.java
  CultureSpot-ServiceApi/src/main/java/com/culturespot/culturespotserviceapi/core/user/mapper/UserMapper.java
  CultureSpot-ServiceApi/src/main/java/com/culturespot/culturespotserviceapi/core/user/validation/ValidNickname.java
  CultureSpot-ServiceApi/src/main/java/com/culturespot/culturespotserviceapi/core/user/validation/ValidNicknameValidator.java
Labels: 기능 구현, 리팩토링

#64 [CUL-243] 메인화면 최신 이벤트 조회
  CultureSpot-Domain/src/main/java/com/culturespot/culturespotdomain/core/performance/entity/Sort.java
  CultureSpot-Domain/src/main/java/com/culturespot/culturespotdomain/core/performance/repository/PerformanceRepository.java
  CultureSpot-ServiceApi/src/main/java/com/culturespot/culturespotserviceapi/common/dto/Paging.java
  CultureSpot-ServiceApi/src/main/java/com/culturespot/culturespotserviceapi/core/auth/controller/spec/AuthControllerSpec.java
  CultureSpot-ServiceApi/src/main/java/com/culturespot/culturespotserviceapi/core/auth/controller/spec/description/AuthControllerDescription.java
  CultureSpot-ServiceApi/src/main/java/com/culturespot/culturespotserviceapi/core/performance/controller/PerformanceController.java
  CultureSpot-ServiceApi/src/main/java/com/culturespot/culturespotserviceapi/core/performance/controller/spec/PerformanceControllerSpec.java
  CultureSpot-ServiceApi/src/main/java/com/culturespot/culturespotserviceapi/core/performance/controller/spec/description/PerformanceControllerDescription.java
  CultureSpot-ServiceApi/src/main/java/com/culturespot/culturespotserviceapi/core/performance/dto/response/PerformanceListResponse.java
  CultureSpot-ServiceApi/src/main/java/com/culturespot/culturespotserviceapi/core/performance/dto/response/PerformanceResponse.java
  CultureSpot-ServiceApi/src/main/java/com/culturespot/culturespotserviceapi/core/performance/service/PerformanceService.java
Labels: 기능 구현
